### ISSUE TITLE
platform-master-20170818100407 does not define API

### ISSUE THREAD

**Issue by ppisar** [modularity-modules/platform-placeholder#1]
The latest platform module build (platform-master-20170818100407) has empty API section. This prevents from programmatic searching for available components among existing modules.

**Comment by KarstenHopp** [comment]
This repository is not the 'real' platform repository.
This issue should be reported in https://github.com/fedora-modularity/hp

**Comment by ppisar** [comment]
Copied to <https://github.com/fedora-modularity/hp/issues/15>.
